import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { Layout } from './components/Layout';
import { ProgressBar } from './components/ProgressBar';
import { courses, preFoundationLessons, testimonials } from './data/platform';
import { QUIZ_DURATION_SECONDS, questions } from './data/questions';
import type { QuizProgress, QuizResult } from './types/quiz';
import type { PlatformState } from './types/platform';
import { calculateResult, formatTime, getEvaluation } from './utils/quiz';
import { clearProgress, clearResult, loadProgress, loadResult, saveProgress, saveResult } from './utils/storage';
import { loadPlatformState, savePlatformState } from './utils/platformStorage';
import './styles.css';

type Page = 'home' | 'login' | 'signup' | 'dashboard' | 'courses' | 'course' | 'lesson' | 'tests' | 'start' | 'quiz' | 'result' | 'review' | 'profile' | 'notfound';

const blankProgress = (studentName = ''): QuizProgress => ({ studentName, answers: {}, currentQuestionIndex: 0, timeRemaining: QUIZ_DURATION_SECONDS, startedAt: new Date().toISOString(), completed: false });
const percent = (done: number, total: number) => Math.round((done / total) * 100);
const dateText = (iso: string) => new Intl.DateTimeFormat('ar-SA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(iso));

function App() {
  const [page, setPage] = useState<Page>('home');
  const [loading, setLoading] = useState(false);
  const [platform, setPlatform] = useState<PlatformState>(() => loadPlatformState());
  const [activeLessonId, setActiveLessonId] = useState(platform.lastLessonId || preFoundationLessons[0].id);
  const [progress, setProgress] = useState<QuizProgress>(() => loadProgress() ?? blankProgress(platform.student.name));
  const [result, setResult] = useState<QuizResult | null>(() => loadResult());
  const [hasSavedAttempt, setHasSavedAttempt] = useState(false);
  const current = questions[progress.currentQuestionIndex] ?? questions[0];
  const savedResult = result ?? loadResult();
  const completedCount = preFoundationLessons.filter((l) => platform.completedLessons.includes(l.id)).length;
  const overallProgress = percent(completedCount, preFoundationLessons.length);
  const currentLesson = preFoundationLessons.find((lesson) => lesson.id === activeLessonId) ?? preFoundationLessons[0];
  const currentLessonIndex = preFoundationLessons.findIndex((lesson) => lesson.id === currentLesson.id);

  const navigate = (next: Page) => { setLoading(true); window.setTimeout(() => { setPage(next); setLoading(false); }, 180); };
  const updatePlatform = (next: PlatformState) => { setPlatform(next); savePlatformState(next); };

  useEffect(() => { const saved = loadProgress(); setHasSavedAttempt(Boolean(saved && !saved.completed)); }, []);
  useEffect(() => { if (page === 'quiz') saveProgress(progress); }, [progress, page]);
  useEffect(() => {
    if (page !== 'quiz') return;
    if (progress.timeRemaining <= 0) { finishQuiz(true); return; }
    const timer = window.setInterval(() => setProgress((p) => ({ ...p, timeRemaining: p.timeRemaining - 1 })), 1000);
    return () => window.clearInterval(timer);
  }, [page, progress.timeRemaining]);

  const answeredCount = useMemo(() => questions.filter((q) => progress.answers[q.id] !== undefined).length, [progress.answers]);
  const unanswered = questions.filter((q) => progress.answers[q.id] === undefined);

  const startNew = (name = platform.student.name) => { clearResult(); setResult(null); const next = blankProgress(name.trim()); setProgress(next); saveProgress(next); navigate('quiz'); setHasSavedAttempt(false); };
  const resume = () => { const saved = loadProgress(); if (saved) { setProgress(saved); navigate('quiz'); } };
  const finishQuiz = (force = false) => {
    if (!force && unanswered.length > 0 && !window.confirm(`لديك ${unanswered.length} سؤال/أسئلة غير مجابة. هل تريد إنهاء الاختبار الآن؟`)) return;
    const nextResult = calculateResult(progress.studentName || platform.student.name, progress.answers);
    saveResult(nextResult); saveProgress({ ...progress, completed: true }); setResult(nextResult); navigate('result'); setHasSavedAttempt(false);
  };
  const logout = () => { updatePlatform({ ...platform, isLoggedIn: false }); navigate('home'); };
  const goLesson = (lessonId: string) => { setActiveLessonId(lessonId); updatePlatform({ ...platform, lastLessonId: lessonId }); navigate('lesson'); };
  const markLessonDone = () => { if (!platform.completedLessons.includes(currentLesson.id)) updatePlatform({ ...platform, completedLessons: [...platform.completedLessons, currentLesson.id], lastLessonId: currentLesson.id }); };

  return <Layout page={page} onNavigate={navigate} onLogout={logout} isLoggedIn={platform.isLoggedIn}>
    {loading && <div className="loading">جاري التحميل...</div>}
    {!loading && <>
      {page === 'home' && <Home onNavigate={navigate} progress={overallProgress} />}
      {page === 'login' && <Auth title="تسجيل الدخول" cta="تسجيل الدخول" signup onSubmit={(name, email, password) => { updatePlatform({ ...platform, student: { name: name || 'طالب هتّاش', email, password }, isLoggedIn: true }); navigate('dashboard'); }} onNavigate={navigate} />}
      {page === 'signup' && <Auth title="إنشاء حساب تجريبي" cta="إنشاء الحساب" confirm signup={false} onSubmit={(name, email, password) => { updatePlatform({ ...platform, student: { name, email, password }, isLoggedIn: true }); navigate('dashboard'); }} onNavigate={navigate} />}
      {page === 'dashboard' && <Dashboard platform={platform} overallProgress={overallProgress} result={savedResult} onNavigate={navigate} onLesson={() => goLesson(platform.lastLessonId)} />}
      {page === 'courses' && <Courses completed={platform.completedLessons} onNavigate={navigate} />}
      {page === 'course' && <CourseDetails completed={platform.completedLessons} onLesson={goLesson} />}
      {page === 'lesson' && <LessonPage lesson={currentLesson} index={currentLessonIndex} completed={platform.completedLessons.includes(currentLesson.id)} onDone={markLessonDone} onLesson={goLesson} onTest={() => navigate('start')} />}
      {page === 'tests' && <Tests result={savedResult} hasSavedAttempt={hasSavedAttempt} onStart={() => navigate('start')} onResume={resume} onReview={() => navigate('review')} />}
      {page === 'start' && <StartPage name={progress.studentName} setName={(studentName) => setProgress((p) => ({ ...p, studentName }))} start={() => startNew(progress.studentName)} back={() => navigate('tests')} />}
      {page === 'quiz' && current && <QuizPage progress={progress} current={current} answeredCount={answeredCount} setProgress={setProgress} finishQuiz={finishQuiz} />}
      {page === 'result' && savedResult && <ResultPage result={savedResult} onReview={() => navigate('review')} onRetry={() => startNew(progress.studentName)} onHome={() => navigate('dashboard')} />}
      {page === 'review' && savedResult && <ReviewPage result={savedResult} onResult={() => navigate('result')} onHome={() => navigate('tests')} />}
      {page === 'profile' && <Profile platform={platform} overallProgress={overallProgress} result={savedResult} onLogout={logout} />}
      {page === 'notfound' && <NotFound onNavigate={navigate} />}
    </>}
  </Layout>;
}

function Home({ onNavigate, progress }: { onNavigate: (p: Page) => void; progress: number }) { return <><section className="hero card"><p className="eyebrow">نموذج أولي عربي متكامل</p><h1>منصة هتّاش التعليمية</h1><p className="tagline">تأسيس قوي | فهم عميق | تفوق مستمر</p><p className="lead">منصة تجريبية تجمع الدورات، الدروس، الاختبارات، النتائج، والمتابعة الشخصية في تجربة RTL حديثة محفوظة محليًا.</p><div className="hero-actions"><button onClick={() => onNavigate('login')}>تسجيل الدخول</button><button className="ghost" onClick={() => onNavigate('courses')}>تصفح الدورات</button></div></section><section className="grid three"><Info title="تعلم منظم" text="مسارات واضحة ودروس قصيرة قابلة للمتابعة." /><Info title="اختبارات فورية" text="المؤقت والنتيجة والمراجعة التفصيلية كما في النظام الحالي." /><Info title="تقدم محفوظ" text={`إنجازك الحالي ${progress}% ومحفوظ عبر localStorage.`} /></section><CoursesPreview onNavigate={onNavigate} /><section><h2>آراء الطلاب</h2><div className="grid three">{testimonials.map((t) => <article className="card mini" key={t.name}><p>“{t.text}”</p><strong>{t.name}</strong></article>)}</div></section></>; }
function Info({ title, text }: { title: string; text: string }) { return <article className="card mini"><span className="icon">◆</span><h3>{title}</h3><p>{text}</p></article>; }
function CoursesPreview({ onNavigate }: { onNavigate: (p: Page) => void }) { return <section><div className="section-head"><h2>الدورات المتاحة</h2><button className="ghost" onClick={() => onNavigate('courses')}>كل الدورات</button></div><div className="grid three">{courses.map((c) => <CourseCard key={c.id} course={c} completed={[]} onOpen={() => onNavigate(c.id === 'pre-foundation' ? 'course' : 'courses')} />)}</div></section>; }
function Auth({ title, cta, confirm, signup, onSubmit, onNavigate }: { title: string; cta: string; confirm?: boolean; signup: boolean; onSubmit: (n: string, e: string, p: string) => void; onNavigate: (p: Page) => void }) { const [name, setName] = useState(''); const [email, setEmail] = useState('student@hattash.test'); const [password, setPassword] = useState('123456'); const [password2, setPassword2] = useState('123456'); return <section className="card narrow form"><h1>{title}</h1>{confirm && <label>الاسم<input value={name} onChange={(e) => setName(e.target.value)} placeholder="اسم الطالب" /></label>}<label>البريد الإلكتروني<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" /></label><label>كلمة المرور<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" /></label>{confirm && <label>تأكيد كلمة المرور<input value={password2} onChange={(e) => setPassword2(e.target.value)} type="password" /></label>}<button onClick={() => password === password2 ? onSubmit(name || 'طالب هتّاش', email, password) : alert('كلمتا المرور غير متطابقتين')}>{cta}</button><button className="link" onClick={() => onNavigate(signup ? 'signup' : 'login')}>{signup ? 'إنشاء حساب' : 'لديك حساب؟ تسجيل الدخول'}</button><p className="hint">بيانات تجريبية فقط بدون Backend.</p></section>; }
function Dashboard({ platform, overallProgress, result, onNavigate, onLesson }: { platform: PlatformState; overallProgress: number; result: QuizResult | null; onNavigate: (p: Page) => void; onLesson: () => void }) { return <section className="stack"><div className="card hero"><p className="eyebrow">لوحة الطالب</p><h1>مرحبًا، {platform.student.name}</h1><ProgressBar value={overallProgress} /><p>نسبة الإنجاز: <strong>{overallProgress}%</strong> — آخر درس: <strong>{preFoundationLessons.find((l) => l.id === platform.lastLessonId)?.title}</strong></p><button onClick={onLesson}>متابعة التعلم</button></div><div className="grid three"><Info title="الدورات المسجلة" text="ما قبل التأسيس، تأسيس القدرات الكمي" /><Info title="الاختبارات المتاحة" text="اختبار تجريبي مرتبط بالدورة" /><Info title="آخر النتائج" text={result ? `${result.percentage}% بتاريخ ${dateText(result.completedAt)}` : 'لا توجد نتيجة بعد'} /></div><button className="ghost" onClick={() => onNavigate('tests')}>الانتقال للاختبارات</button></section>; }
function Courses({ completed, onNavigate }: { completed: string[]; onNavigate: (p: Page) => void }) { return <section><div className="section-head"><h1>الدورات</h1><button onClick={() => onNavigate('course')}>تفاصيل ما قبل التأسيس</button></div><div className="grid three">{courses.map((c) => <CourseCard key={c.id} course={c} completed={completed} onOpen={() => c.id === 'pre-foundation' ? onNavigate('course') : alert('صفحة التفاصيل الكاملة ستتوفر لاحقًا، والدورة ظاهرة كنموذج تجريبي.')} />)}</div></section>; }
function CourseCard({ course, completed, onOpen }: { course: typeof courses[number]; completed: string[]; onOpen: () => void }) { const done = course.lessons.filter((l) => completed.includes(l.id)).length; return <article className="card course-card"><div className="course-art"><span>{course.accent}</span></div><h2>{course.title}</h2><p>{course.description}</p><p>{course.lessons.length} دروس</p><ProgressBar value={percent(done, course.lessons.length)} /><button onClick={onOpen}>عرض الدورة</button></article>; }
function CourseDetails({ completed, onLesson }: { completed: string[]; onLesson: (id: string) => void }) { return <section className="card"><p className="eyebrow">تفاصيل الدورة</p><h1>ما قبل التأسيس</h1><p className="lead">دورة تأسيسية تعالج الفجوات الحسابية قبل دراسة القدرات الكمي.</p><div className="lesson-list">{preFoundationLessons.map((l) => <button className="lesson-row" key={l.id} onClick={() => onLesson(l.id)}><span>{l.title}<small>{l.description}</small></span><strong>{completed.includes(l.id) ? 'مكتمل' : 'غير مكتمل'}</strong></button>)}</div></section>; }
function LessonPage({ lesson, index, completed, onDone, onLesson, onTest }: { lesson: typeof preFoundationLessons[number]; index: number; completed: boolean; onDone: () => void; onLesson: (id: string) => void; onTest: () => void }) { return <section className="card lesson"><div className="video">فيديو تجريبي — {lesson.title}</div><p className="eyebrow">درس {index + 1}</p><h1>{lesson.title}</h1><p className="lead">{lesson.description}</p><div className="actions"><button className="ghost" disabled={index === 0} onClick={() => onLesson(preFoundationLessons[index - 1].id)}>الدرس السابق</button><button className="ghost" disabled={index === preFoundationLessons.length - 1} onClick={() => onLesson(preFoundationLessons[index + 1].id)}>الدرس التالي</button><button onClick={onDone}>{completed ? 'تم إكمال الدرس' : 'تحديد الدرس كمكتمل'}</button><button onClick={onTest}>اختبار الدرس</button></div><div className="training-file">📄 ملف تدريبي تجريبي: ملخص وأسئلة قصيرة للدرس.</div></section>; }
function Tests({ result, hasSavedAttempt, onStart, onResume, onReview }: { result: QuizResult | null; hasSavedAttempt: boolean; onStart: () => void; onResume: () => void; onReview: () => void }) { return <section className="stack"><div className="card"><h1>الاختبارات</h1><p>الاختبار الحالي مرتبط بدورة ما قبل التأسيس ويحتفظ بالمؤقت والمراجعة والنتيجة.</p><div className="quiz-card"><div><h2>اختبار درس ما قبل التأسيس</h2><p>{questions.length} سؤالًا — 10 دقائق — تصحيح فوري.</p></div><div className="actions"><button onClick={onStart}>بدء الاختبار</button>{hasSavedAttempt && <button className="ghost" onClick={onResume}>متابعة المحاولة</button>}</div></div></div><div className="card"><h2>نتائج الطالب</h2>{result ? <p>آخر نتيجة: <strong>{result.score}/{result.total}</strong> ({result.percentage}%) <button className="ghost" onClick={onReview}>مراجعة</button></p> : <p>لا توجد نتائج محفوظة بعد.</p>}</div></section>; }
function StartPage({ name, setName, start, back }: { name: string; setName: (v: string) => void; start: () => void; back: () => void }) { return <section className="card narrow"><h1>بداية الاختبار</h1><label>اسم الطالب <span>(اختياري)</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="اكتب اسمك هنا" /></label><div className="instructions"><h2>تعليمات مختصرة</h2><p>سيظهر سؤال واحد في كل مرة. يمكنك الانتقال بين الأسئلة، وسيتم حفظ تقدمك محليًا إذا أغلقت الصفحة.</p><p>عدد الأسئلة: <strong>{questions.length}</strong> — مدة الاختبار: <strong>10 دقائق</strong></p></div><button onClick={start}>بدء الاختبار</button><button className="ghost" onClick={back}>العودة للاختبارات</button></section>; }
function QuizPage({ progress, current, answeredCount, setProgress, finishQuiz }: { progress: QuizProgress; current: typeof questions[number]; answeredCount: number; setProgress: Dispatch<SetStateAction<QuizProgress>>; finishQuiz: (f?: boolean) => void }) { return <section className="card quiz"><div className="quiz-head"><div><strong>السؤال {progress.currentQuestionIndex + 1} من {questions.length}</strong><p>{answeredCount} إجابة محفوظة</p></div><div className="timer">{formatTime(progress.timeRemaining)}</div></div><ProgressBar value={(answeredCount / questions.length) * 100} /><div className="jump-list">{questions.map((q, index) => <button key={q.id} className={index === progress.currentQuestionIndex ? 'active' : progress.answers[q.id] !== undefined ? 'answered' : ''} onClick={() => setProgress((p) => ({ ...p, currentQuestionIndex: index }))}>{index + 1}</button>)}</div><p className="category">{current.category}</p><h1>{current.text}</h1><div className="options">{current.options.map((option, index) => <button key={option} className={progress.answers[current.id] === index ? 'selected' : ''} onClick={() => setProgress((p) => ({ ...p, answers: { ...p.answers, [current.id]: index } }))}>{option}</button>)}</div><div className="actions"><button className="ghost" disabled={progress.currentQuestionIndex === 0} onClick={() => setProgress((p) => ({ ...p, currentQuestionIndex: p.currentQuestionIndex - 1 }))}>السابق</button>{progress.currentQuestionIndex < questions.length - 1 ? <button onClick={() => setProgress((p) => ({ ...p, currentQuestionIndex: p.currentQuestionIndex + 1 }))}>التالي</button> : <button onClick={() => finishQuiz(false)}>إنهاء الاختبار</button>}</div></section>; }
function ResultPage({ result, onReview, onRetry, onHome }: { result: QuizResult; onReview: () => void; onRetry: () => void; onHome: () => void }) { return <section className="card result"><h1>نتيجة الاختبار</h1>{result.studentName && <p>الطالب: <strong>{result.studentName}</strong></p>}<div className="score">{result.score} / {result.total}<span>{result.percentage}%</span></div><div className="stats"><span>صحيحة: {result.correct}</span><span>خاطئة: {result.wrong}</span><span>غير مجابة: {result.unanswered}</span></div><p className="evaluation">{getEvaluation(result.percentage)}</p><div className="actions"><button onClick={onReview}>مراجعة الإجابات</button><button className="ghost" onClick={onRetry}>إعادة الاختبار</button><button className="ghost" onClick={onHome}>لوحة الطالب</button></div></section>; }
function ReviewPage({ result, onResult, onHome }: { result: QuizResult; onResult: () => void; onHome: () => void }) { return <section className="review"><div className="review-header"><h1>مراجعة الإجابات</h1><div><button onClick={onResult}>النتيجة</button><button className="ghost" onClick={onHome}>الاختبارات</button></div></div>{questions.map((q) => { const chosen = result.answers[q.id]; const isCorrect = chosen === q.correctAnswer; return <article className="card review-item" key={q.id}><p className="category">{q.category}</p><h2>{q.id}. {q.text}</h2><p>اختيار الطالب: <strong>{chosen === undefined ? 'لم تتم الإجابة' : q.options[chosen]}</strong></p><p>الإجابة الصحيحة: <strong>{q.options[q.correctAnswer]}</strong></p><p className={isCorrect ? 'correct' : 'wrong'}>{isCorrect ? 'إجابة صحيحة' : 'إجابة خاطئة أو غير مجابة'}</p><p className="explanation">التفسير: {q.explanation}</p></article>; })}</section>; }
function Profile({ platform, overallProgress, result, onLogout }: { platform: PlatformState; overallProgress: number; result: QuizResult | null; onLogout: () => void }) { return <section className="card narrow"><h1>الملف الشخصي</h1><p><strong>الاسم:</strong> {platform.student.name}</p><p><strong>البريد:</strong> {platform.student.email}</p><ProgressBar value={overallProgress} /><p>الإنجاز العام: {overallProgress}%</p><h2>سجل النتائج</h2>{result ? <p>{result.percentage}% — {dateText(result.completedAt)}</p> : <p>لا يوجد سجل نتائج بعد.</p>}<button onClick={onLogout}>تسجيل الخروج</button></section>; }
function NotFound({ onNavigate }: { onNavigate: (p: Page) => void }) { return <section className="card narrow"><h1>404</h1><p>الصفحة غير موجودة في النموذج التجريبي.</p><button onClick={() => onNavigate('home')}>العودة للرئيسية</button></section>; }

export default App;
